{
 "title": "Sonarqube Dashboard",
 "description": "SonarQube (Prometheus) dashboard developed by FuchiCorp.",
 "tags": [
  "sonar-qube",
  "common-tools"
 ],
 "time": { "from": "2021-05-14T05:30:46.251Z", "to": "2021-05-14T08:54:11.642Z" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"tools\",pod=~\"sonarqube-tools-sonarqube.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "PostgreSQL_pod_status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=\"sonarqube-tools-postgresql\",namespace=\"tools\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "grad" } },
   "yaxes": [
    { "format": "grad" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"tools\",pod=~\"sonarqube-tools-sonarqube.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"tools\",pod=~\"sonarqube-tools-sonarqube.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"tools\",pod=~\"sonarqube-tools-sonarqube.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"sonarqube-tools-sonarqube\",namespace=\"tools\"}",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"sonarqube-tools-sonarqube\",namespace=\"tools\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation{deployment=\"sonarqube-tools-sonarqube\",namespace=\"tools\"}\t"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"tools\"})"
    }
   ]
  }
 ]
}