{
 "title": "Waypoint Dashboard",
 "description": "Waypoint (Prometheus) dashboard developed by FuchiCorp.",
 "tags": [
  "waypoint",
  "common-tools"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "tools" },
   { "name": "pod", "label": "Pod", "query": "waypoint-tools-0" },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"tools\", pod=~\"waypoint-tools-0\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Count (Namespace)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"tools\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"tools\",pod=~\"waypoint-tools-0\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"tools\", pod=~\"waypoint-tools-0\", container=~\"waypoint\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"tools\",pod=~\"waypoint-tools-0\",container=~\"waypoint\",container!=\"POD\",image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{pod=~\"waypoint-tools-0\", container=~\"waypoint\", image!=\"\", container!=\"POD\", image!=\"\"}[2m]))",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"waypoint-tools-0\", container=~\"waypoint\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"waypoint-tools-0\", container=~\"waypoint\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"tools\", pod=~\"waypoint-tools-0\",container=~\"waypoint\", container!=\"POD\", container!=\"\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{pod=~\"waypoint-tools-0\", container=~\"waypoint\", container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"waypoint-tools-0\", container=~\"waypoint\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"waypoint-tools-0\", container=~\"waypoint\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network RX/TX Total (bytes/sec)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"tools\",pod=~\"waypoint-tools-0\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"tools\",pod=~\"waypoint-tools-0\"}[5m])) "
    }
   ]
  },
  {
   "title": "POD Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_transmit_bytes_total{pod=~\"waypoint-tools-0\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate (container_network_receive_bytes_total{pod=~\"waypoint-tools-0\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  }
 ]
}